# Doc:
# https://alacritty.org/config-alacritty.html

[general]
import = [
    "~/.alacritty-theme-default.toml"
]

[window]
position = { x = 20, y = 250 }
dimensions = { columns = 180, lines = 40 }
padding.x = 16
padding.y = 14
opacity = 0.9
# decorations = "none" # Removes the window decoration (title bar, etc.)

[font]
size = 13
